---
title: "Homework 3"
author: "Yingting Zhang"
date: "2023-10-11"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```


# Question 2

```{r}
library(p8105.datasets)
data("brfss_smart2010")
```


## Data cleaning

```{r}
brfss = brfss_smart2010 |> 
  janitor::clean_names() |> 
  filter(topic == "Overall Health") |> 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) |>
  mutate(
    response = forcats::fct_relevel(response, c("Poor","Fair","Good","Very good","Excellent"))
  ) |> rename(state = locationabbr) |> rename(county = locationdesc)
```


# In 2002, which states were observed at 7 or more locations? What about in 2010?

```{r}
brfss_2002 = brfss |> 
  filter(year =="2002") |> 
  group_by(state) |> 
  summarise(n_obs = n_distinct(county)) |> 
  filter(n_obs >= 7)

brfss_2010 = brfss |> 
  filter(year =="2010") |> 
  group_by(state) |> 
  summarise(n_obs = n_distinct(county)) |> 
  filter(n_obs >= 7)
```

In 2002, **`r print(pull(brfss_2002,state))`** were observed at 7 or more locations.
In 2010, **`r print(pull(brfss_2010,state))`** were observed at 7 or more locations.


# Construct a dataset

```{r}
brfss_conduct = brfss |> 
  filter(response =="Excellent") |> 
  group_by(year,state) |> 
  summarise(
    mean_value = mean(data_value,na.rm = TRUE),.groups = "drop") |> 
  ggplot(aes(x = year, y = mean_value, color = state))+ geom_line()
  
```


# Make a two-panel plot showing


```{r}
brfss_panel= brfss |> 
  filter(year %in% c("2006", "2010")) |> 
  filter(state == "NY") |> 
  ggplot(aes(x = response, y = data_value)) + geom_boxplot()+
  facet_grid(.~ year)
  
```


